### PR TITLE
add namespace functionality on planning_scene_interface.py

### PR DESCRIPTION
**Pull request by Benjamin-Tan**
As mentioned in the title, I used planning scene interface for multiple robot planning and visualisation. Hence there is a need for me to use planning scene at different namespace (e.g. robot1/planning_scene and robot2/planning_scene and etc). Hope you will find this useful.

### CODE REVIEW

**Comment by Benjamin-Tan** [comment]
I have updated the code with your comments in the new commit.

**Comment by mikeferguson** [comment]
I manually merged this, since I totally borked the PR with conflicts after merging the apply service portion

**Comment by mikeferguson** [comment]
https://github.com/mikeferguson/moveit_python/commit/0fdf7620c5f36866f5f101b818c4a330ebee3155

**Comment by Benjamin-Tan** [comment]
Hi @mikeferguson, sorry for the incomplete pull request, as I have found another small issue with the namespacing on Line 65. 

I carelessly miss this line on adding the namespace. Could you please kindly change from:
self._apply_service = rospy.ServiceProxy('apply_planning_scene', ApplyPlanningScene) to  self._apply_service = rospy.ServiceProxy(ns + 'apply_planning_scene', ApplyPlanningScene)?

many thanks.

**Comment by mikeferguson** [comment]
Actually -- that line is from me merging in the ApplyPlanningScene stuff -- updated in master.

**Comment by Benjamin-Tan** [comment]
I just realised that too, as I was pulling the latest repo for my machine, and found out this problem. Just to let you know that my small fix for namespacing is this. :)

**Pull request closed without merging**
